// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjnusrmejrsjgwcyvhmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqbnVzcm1lanJzamd3Y3l2aG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzc5MjAsImV4cCI6MjA3MzYxMzkyMH0.bxVdR-WHAYdk3iEb7Ukuf4t7ff8N4tXTG-DdCGbVEJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});